name: Build vLLM Windows Wheel

on:
  push:
    tags:
      - "v*"

jobs:
  build-wheel:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10", "3.12"]
        cuda: [
          "12.4.1|cu124|https://developer.download.nvidia.com/compute/cuda/12.4.1/local_installers/cuda_12.4.1_551.78_windows.exe",
          "12.6.3|cu126|https://developer.download.nvidia.com/compute/cuda/12.6.3/local_installers/cuda_12.6.3_561.17_windows.exe"
        ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Parse CUDA matrix
        shell: pwsh
        run: |
          $parts = "${{ matrix.cuda }}" -split '\|'
          echo "CUDA_VER=$($parts[0])" >> $env:GITHUB_ENV
          echo "CUDA_TAG=$($parts[1])" >> $env:GITHUB_ENV
          echo "CUDA_URL=$($parts[2])" >> $env:GITHUB_ENV

      - name: Download and Install CUDA
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri $env:CUDA_URL -OutFile C:\cuda_installer.exe
          Test-Path "C:\cuda_installer.exe"
          & "C:\cuda_installer.exe" --silent --toolkit --override
          Get-ChildItem "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA" -Directory | ForEach-Object { $_.Name }
          echo "CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v$($env:CUDA_VER.Substring(0,4))" >> $env:GITHUB_ENV
          echo "PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v$($env:CUDA_VER.Substring(0,4))\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v$($env:CUDA_VER.Substring(0,4))\libnvvp;$env:PATH" >> $env:GITHUB_ENV
          nvcc --version

      - name: Init MSVC Environment and Build
        shell: pwsh
        run: |
          $vsPath = & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
          & "$vsPath\VC\Auxiliary\Build\vcvarsall.bat" x64
          $env:DISTUTILS_USE_SDK = "1"
          $env:VLLM_TARGET_DEVICE = "cuda"
          $env:MAX_JOBS = "4"
          python -m pip install --upgrade pip
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/$env:CUDA_TAG
          pip install -r requirements/build.txt
          pip install -r requirements/windows.txt
          pip wheel . --no-build-isolation -w dist
          $distDir = "dist_$($env:CUDA_TAG)_py$($env:PYTHON_VERSION)"
          New-Item -ItemType Directory -Path $distDir -Force
          Move-Item -Path "dist\*.whl" -Destination $distDir

      - name: Upload wheel to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist_$env:CUDA_TAG_py$env:PYTHON_VERSION/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
